In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, X):
    return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

In [5]:
# 带参数的层
class MyLinear(nn.Module):
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units))
    self.bias = nn.Parameter(torch.randn(units,))
  def forward(self, X):
    linear = torch.matmul(X, self.weight.data) + self.bias.data
    return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.4657, -0.4967,  1.8614],
        [-0.5542, -2.3917, -0.7292],
        [-0.1856, -0.6406,  0.2642],
        [ 0.4206,  0.2457, -0.2533],
        [ 0.5271,  0.9684,  0.1973]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 1.1547],
        [0.0000, 0.0000, 1.2618]])